services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 8081:8081
    volumes:
      - mongodb:/data/db
  typesense:
    container_name: typesense
    image: typesense/typesense:0.25.1
    ports:
      - 8108:8108
    volumes:
      - typesense:/data
    command: "--data-dir=/data --api-key=xyz --enable-search-analytics=true --analytics-flush-interval=60 --enable-cors"

volumes:
  mongodb:
  typesense:
